module Immobilier {
    struct Bien {
        long id;
        string titre;
        string description;
        double prix;
        boolean disponible;
        long agentId;
    };

    typedef sequence<Bien> BienSeq;

    interface BienService {
        long addBien(in Bien b);
        BienSeq listBiens();
        BienSeq listBiensAgent(in long agentId);
        boolean checkDisponibilite(in long bienId);
    };
};
