package Immobilier;


/**
* Immobilier/BienSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

public final class BienSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Immobilier.Bien value[] = null;

  public BienSeqHolder ()
  {
  }

  public BienSeqHolder (Immobilier.Bien[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Immobilier.BienSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Immobilier.BienSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Immobilier.BienSeqHelper.type ();
  }

}
