package Immobilier;


/**
* Immobilier/BienService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Immobilier.idl
* dimanche 7 décembre 2025 15 h 44 WAT
*/

public interface BienService extends BienServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BienService
