package Immobilier;


/**
* Immobilier/BienService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* samedi 6 décembre 2025 20 h 39 WAT
*/

public interface BienService extends BienServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BienService
