package Immobilier;


/**
* Immobilier/BienSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* samedi 6 décembre 2025 20 h 39 WAT
*/

abstract public class BienSeqHelper
{
  private static String  _id = "IDL:Immobilier/BienSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, Immobilier.Bien[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Immobilier.Bien[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Immobilier.BienHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Immobilier.BienSeqHelper.id (), "BienSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Immobilier.Bien[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Immobilier.Bien value[] = null;
    int _len0 = istream.read_long ();
    value = new Immobilier.Bien[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Immobilier.BienHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Immobilier.Bien[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Immobilier.BienHelper.write (ostream, value[_i0]);
  }

}
