package Immobilier;


/**
* Immobilier/BienServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

public abstract class BienServicePOA extends org.omg.PortableServer.Servant
 implements Immobilier.BienServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addBien", new java.lang.Integer (0));
    _methods.put ("listBiens", new java.lang.Integer (1));
    _methods.put ("checkDisponibilite", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Immobilier/BienService/addBien
       {
         Immobilier.Bien b = Immobilier.BienHelper.read (in);
         int $result = (int)0;
         $result = this.addBien (b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Immobilier/BienService/listBiens
       {
         Immobilier.Bien $result[] = null;
         $result = this.listBiens ();
         out = $rh.createReply();
         Immobilier.BienSeqHelper.write (out, $result);
         break;
       }

       case 2:  // Immobilier/BienService/checkDisponibilite
       {
         int bienId = in.read_long ();
         boolean $result = false;
         $result = this.checkDisponibilite (bienId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Immobilier/BienService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BienService _this() 
  {
    return BienServiceHelper.narrow(
    super._this_object());
  }

  public BienService _this(org.omg.CORBA.ORB orb) 
  {
    return BienServiceHelper.narrow(
    super._this_object(orb));
  }


} // class BienServicePOA
