package Immobilier;


/**
* Immobilier/Bien.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Immobilier.idl
* dimanche 7 décembre 2025 15 h 44 WAT
*/

public final class Bien implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String titre = null;
  public String description = null;
  public double prix = (double)0;
  public boolean disponible = false;
  public int agentId = (int)0;

  public Bien ()
  {
  } // ctor

  public Bien (int _id, String _titre, String _description, double _prix, boolean _disponible, int _agentId)
  {
    id = _id;
    titre = _titre;
    description = _description;
    prix = _prix;
    disponible = _disponible;
    agentId = _agentId;
  } // ctor

} // class Bien
