package Immobilier;


/**
* Immobilier/BienServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* samedi 6 décembre 2025 20 h 39 WAT
*/

public interface BienServiceOperations 
{
  int addBien (Immobilier.Bien b);
  Immobilier.Bien[] listBiens ();
  Immobilier.Bien[] listBiensAgent (int agentId);
  boolean checkDisponibilite (int bienId);
} // interface BienServiceOperations
