package Immobilier;


/**
* Immobilier/BienServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Immobilier.idl
* dimanche 7 d�cembre 2025 15 h 44 WAT
*/

public abstract class BienServicePOA extends org.omg.PortableServer.Servant
 implements Immobilier.BienServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addBien", Integer.valueOf(0));
    _methods.put ("listBiens", Integer.valueOf(1));
    _methods.put ("listBiensAgent", Integer.valueOf(2));
    _methods.put ("checkDisponibilite", Integer.valueOf(3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Immobilier/BienService/addBien
       {
         Immobilier.Bien b = Immobilier.BienHelper.read (in);
         int $result = (int)0;
         $result = Math.toIntExact(this.addBien(b));
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Immobilier/BienService/listBiens
       {
         Immobilier.Bien $result[] = null;
         $result = this.listBiens ();
         out = $rh.createReply();
         Immobilier.BienSeqHelper.write (out, $result);
         break;
       }

       case 2:  // Immobilier/BienService/listBiensAgent
       {
         int agentId = in.read_long ();
         Immobilier.Bien $result[] = null;
         $result = this.listBiensAgent (agentId);
         out = $rh.createReply();
         Immobilier.BienSeqHelper.write (out, $result);
         break;
       }

       case 3:  // Immobilier/BienService/checkDisponibilite
       {
         int bienId = in.read_long ();
         boolean $result = false;
         $result = this.checkDisponibilite (bienId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Immobilier/BienService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BienService _this() 
  {
    return BienServiceHelper.narrow(
    super._this_object());
  }

  public BienService _this(org.omg.CORBA.ORB orb) 
  {
    return BienServiceHelper.narrow(
    super._this_object(orb));
  }


} // class BienServicePOA
