package Immobilier;


/**
* Immobilier/BienHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

abstract public class BienHelper
{
  private static String  _id = "IDL:Immobilier/Bien:1.0";

  public static void insert (org.omg.CORBA.Any a, Immobilier.Bien that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Immobilier.Bien extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "titre",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "description",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "disponible",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Immobilier.BienHelper.id (), "Bien", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Immobilier.Bien read (org.omg.CORBA.portable.InputStream istream)
  {
    Immobilier.Bien value = new Immobilier.Bien ();
    value.id = istream.read_long ();
    value.titre = istream.read_string ();
    value.description = istream.read_string ();
    value.disponible = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Immobilier.Bien value)
  {
    ostream.write_long (value.id);
    ostream.write_string (value.titre);
    ostream.write_string (value.description);
    ostream.write_boolean (value.disponible);
  }

}
