package Immobilier;

/**
* Immobilier/BienHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* samedi 6 décembre 2025 20 h 39 WAT
*/

public final class BienHolder implements org.omg.CORBA.portable.Streamable
{
  public Immobilier.Bien value = null;

  public BienHolder ()
  {
  }

  public BienHolder (Immobilier.Bien initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Immobilier.BienHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Immobilier.BienHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Immobilier.BienHelper.type ();
  }

}
