package Immobilier;


/**
* Immobilier/BienServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

abstract public class BienServiceHelper
{
  private static String  _id = "IDL:Immobilier/BienService:1.0";

  public static void insert (org.omg.CORBA.Any a, Immobilier.BienService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Immobilier.BienService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Immobilier.BienServiceHelper.id (), "BienService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Immobilier.BienService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BienServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Immobilier.BienService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Immobilier.BienService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Immobilier.BienService)
      return (Immobilier.BienService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Immobilier._BienServiceStub stub = new Immobilier._BienServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Immobilier.BienService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Immobilier.BienService)
      return (Immobilier.BienService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Immobilier._BienServiceStub stub = new Immobilier._BienServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
