package Immobilier;

/**
* Immobilier/BienServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* samedi 6 décembre 2025 20 h 39 WAT
*/

public final class BienServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Immobilier.BienService value = null;

  public BienServiceHolder ()
  {
  }

  public BienServiceHolder (Immobilier.BienService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Immobilier.BienServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Immobilier.BienServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Immobilier.BienServiceHelper.type ();
  }

}
