package Immobilier;


/**
* Immobilier/BienServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Immobilier.idl
* dimanche 7 d�cembre 2025 15 h 44 WAT
*/

public interface BienServiceOperations 
{
  long addBien (Bien b);
  Immobilier.Bien[] listBiens ();
  Immobilier.Bien[] listBiensAgent (int agentId);
  boolean checkDisponibilite (int bienId);
} // interface BienServiceOperations
