package Immobilier;


/**
* Immobilier/Bien.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

public final class Bien implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String titre = null;
  public String description = null;
  public boolean disponible = false;

  public Bien ()
  {
  } // ctor

  public Bien (int _id, String _titre, String _description, boolean _disponible)
  {
    id = _id;
    titre = _titre;
    description = _description;
    disponible = _disponible;
  } // ctor

} // class Bien
