package Immobilier;


/**
* Immobilier/BienServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BienService.idl
* vendredi 5 décembre 2025 20 h 15 WAT
*/

public interface BienServiceOperations 
{
  int addBien (Immobilier.Bien b);
  Immobilier.Bien[] listBiens ();
  boolean checkDisponibilite (int bienId);
} // interface BienServiceOperations
