package Immobilier;

/**
 * Immobilier/BienServicePOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from BienService.idl
 * samedi 6 décembre 2025 20 h 39 WAT
 */

public abstract class BienServicePOA extends org.omg.PortableServer.Servant
        implements Immobilier.BienServiceOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors

    private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<>();
    static {
        _methods.put("addBien", 0);
        _methods.put("listBiens", 1);
        _methods.put("listBiensAgent", 2);
        _methods.put("checkDisponibilite", 3);
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        Integer __method = _methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method) {
            case 0:  // Immobilier/BienService/addBien
                Immobilier.Bien b = Immobilier.BienHelper.read(in);
                int $result = this.addBien(b);
                out = $rh.createReply();
                out.write_long($result);
                break;

            case 1:  // Immobilier/BienService/listBiens
                Immobilier.Bien[] $resultList = this.listBiens();
                out = $rh.createReply();
                Immobilier.BienSeqHelper.write(out, $resultList);
                break;

            case 2:  // Immobilier/BienService/listBiensAgent
                int agentId = in.read_long();
                Immobilier.Bien[] $resultAgent = this.listBiensAgent(agentId);
                out = $rh.createReply();
                Immobilier.BienSeqHelper.write(out, $resultAgent);
                break;

            case 3:  // Immobilier/BienService/checkDisponibilite
                int bienId = in.read_long();
                boolean $resultBool = this.checkDisponibilite(bienId);
                out = $rh.createReply();
                out.write_boolean($resultBool);
                break;

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = { "IDL:Immobilier/BienService:1.0" };

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return __ids.clone();
    }

    public BienService _this() {
        return BienServiceHelper.narrow(super._this_object());
    }

    public BienService _this(org.omg.CORBA.ORB orb) {
        return BienServiceHelper.narrow(super._this_object(orb));
    }

} // class BienServicePOA
